-- Supabase SQL for guestbook posts table
create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  name text not null,
  message text not null,
  created_at timestamp with time zone not null default now()
);

alter table if exists public.posts enable row level security;

create policy if not exists "Allow insert for service role"
  on public.posts
  for insert
  with check (true);
